FULLSCREEN_X = 0
FULLSCREEN_Y = 0
FULLSCREEN_W = X * 0.5
FULLSCREEN_H = Y * 0.5
FULLSCREEN_REGION = Region(FULLSCREEN_X, FULLSCREEN_Y, FULLSCREEN_W, FULLSCREEN_H)

CLICK_BLOCK_W = X * 0.01
CLICK_BLOCK_H = X * 0.01

INEMBARKPAGE_X = X * 0.05
INEMBARKPAGE_Y = Y * 0.2
INEMBARKPAGE_W = X * 0.08
INEMBARKPAGE_H = Y * 0.1
INEMBARKPAGE_REGION = Region(INEMBARKPAGE_X, INEMBARKPAGE_Y, INEMBARKPAGE_W, INEMBARKPAGE_H)

AUTOBATTLE_X = X * 0.55
AUTOBATTLE_Y = Y * 0.94
AUTOBATTLE_REGION = Region(AUTOBATTLE_X, AUTOBATTLE_Y, CLICK_BLOCK_W, CLICK_BLOCK_H)

GOCHOOSECOMPANION_X = X * 0.82
GOCHOOSECOMPANION_Y = Y * 0.37
GOCHOOSECOMPANION_REGION = Region(GOCHOOSECOMPANION_X, GOCHOOSECOMPANION_Y, CLICK_BLOCK_W, CLICK_BLOCK_H)

EMBARK_X = X * 0.8
EMBARK_Y = Y * 0.92
EMBARK_REGION = Region(EMBARK_X, EMBARK_Y, CLICK_BLOCK_W, CLICK_BLOCK_H)

INCHOOSECOMPANIONPAGE_X = X * 0.03
INCHOOSECOMPANIONPAGE_Y = Y * 0.1
INCHOOSECOMPANIONPAGE_W = X * 0.08
INCHOOSECOMPANIONPAGE_H = Y * 0.1
INCHOOSECOMPANIONPAGE_REGION = Region(INCHOOSECOMPANIONPAGE_X, INCHOOSECOMPANIONPAGE_Y, INCHOOSECOMPANIONPAGE_W, INCHOOSECOMPANIONPAGE_H)

CHOOSECOMPANION_X = X * 0.38
CHOOSECOMPANION_Y = Y * 0.45
CHOOSECOMPANION_REGION = Region(CHOOSECOMPANION_X, CHOOSECOMPANION_Y, CLICK_BLOCK_W, CLICK_BLOCK_H)

MISSIONCOMPLETE_X = X * 0.05
MISSIONCOMPLETE_Y = Y * 0.25
MISSIONCOMPLETE_W = X * 0.05
MISSIONCOMPLETE_H = Y * 0.1
MISSIONCOMPLETE_REGION = Region(MISSIONCOMPLETE_X, MISSIONCOMPLETE_Y, MISSIONCOMPLETE_W, MISSIONCOMPLETE_H)

MISSIONCOMPLETENEXT_X = X * 0.85
MISSIONCOMPLETENEXT_Y = Y * 0.92
MISSIONCOMPLETENEXT_REGION = Region(MISSIONCOMPLETENEXT_X, MISSIONCOMPLETENEXT_Y, CLICK_BLOCK_W, CLICK_BLOCK_H)

INRESULTPAGE_X = X * 0.28
INRESULTPAGE_Y = Y * 0.13
INRESULTPAGE_W = X * 0.05
INRESULTPAGE_H = Y * 0.1
INRESULTPAGE_REGION = Region(INRESULTPAGE_X, INRESULTPAGE_Y, INRESULTPAGE_W, INRESULTPAGE_H)

EMBARKAGAIN_X = X * 0.55
EMBARKAGAIN_Y = Y * 0.92
EMBARKAGAIN_REGION = Region(EMBARKAGAIN_X, EMBARKAGAIN_Y, CLICK_BLOCK_W, CLICK_BLOCK_H)

RETURNTOEMBARKSCREEN_X = X * 0.38
RETURNTOEMBARKSCREEN_Y = Y * 0.92
RETURNTOEMBARKSCREEN_REGION = Region(RETURNTOEMBARKSCREEN_X, RETURNTOEMBARKSCREEN_Y, CLICK_BLOCK_W, CLICK_BLOCK_H)

SHARDDREACHEDMAX_X = X * 0.12
SHARDDREACHEDMAX_Y = Y * 0.08
SHARDDREACHEDMAX_W = X * 0.05
SHARDDREACHEDMAX_H = Y * 0.1
SHARDDREACHEDMAX_REGION = Region(SHARDDREACHEDMAX_X, SHARDDREACHEDMAX_Y, SHARDDREACHEDMAX_W, SHARDDREACHEDMAX_H)

SHARDDREACHEDMAXOK_X = X * 0.5
SHARDDREACHEDMAXOK_Y = Y * 0.85
SHARDDREACHEDMAXOK_REGION = Region(SHARDDREACHEDMAXOK_X, SHARDDREACHEDMAXOK_Y, CLICK_BLOCK_W, CLICK_BLOCK_H)

INWHIMSYSHOPPAGE_X = X * 0.48
INWHIMSYSHOPPAGE_Y = Y * 0.22
INWHIMSYSHOPPAGE_W = X * 0.05
INWHIMSYSHOPPAGE_H = Y * 0.1
INWHIMSYSHOPPAGE_REGION = Region(INWHIMSYSHOPPAGE_X, INWHIMSYSHOPPAGE_Y, INWHIMSYSHOPPAGE_W, INWHIMSYSHOPPAGE_H)

GOTOWHIMSYSHOP_X = X * 0.55
GOTOWHIMSYSHOP_Y = Y * 0.92
GOTOWHIMSYSHOP_REGION = Region(GOTOWHIMSYSHOP_X, GOTOWHIMSYSHOP_Y, CLICK_BLOCK_W, CLICK_BLOCK_H)

GOTOWHIMSYSHOPLATER_X = X * 0.38
GOTOWHIMSYSHOPLATER_Y = Y * 0.92
GOTOWHIMSYSHOPLATER_REGION = Region(GOTOWHIMSYSHOPLATER_X, GOTOWHIMSYSHOPLATER_Y, CLICK_BLOCK_W, CLICK_BLOCK_H)

INWHIMSYSHOPBUY_X = X * 0.75
INWHIMSYSHOPBUY_Y = Y * 0.1
INWHIMSYSHOPBUY_W = X * 0.05
INWHIMSYSHOPBUY_H = Y * 0.1
INWHIMSYSHOPBUY_REGION = Region(INWHIMSYSHOPBUY_X, INWHIMSYSHOPBUY_Y, INWHIMSYSHOPBUY_W, INWHIMSYSHOPBUY_H)

WHIMSYSHOPBUY1x1_X = X * 0.3
WHIMSYSHOPBUY1x1_Y = Y * 0.2
WHIMSYSHOPBUY1x1_W = X * 0.2
WHIMSYSHOPBUY1x1_H = Y * 0.3
WHIMSYSHOPBUY1x1_REGION = Region(WHIMSYSHOPBUY1x1_X, WHIMSYSHOPBUY1x1_Y, WHIMSYSHOPBUY1x1_W, WHIMSYSHOPBUY1x1_H)

WHIMSYSHOPBUY1x2_X = X * 0.51
WHIMSYSHOPBUY1x2_Y = Y * 0.2
WHIMSYSHOPBUY1x2_W = X * 0.2
WHIMSYSHOPBUY1x2_H = Y * 0.3
WHIMSYSHOPBUY1x2_REGION = Region(WHIMSYSHOPBUY1x2_X, WHIMSYSHOPBUY1x2_Y, WHIMSYSHOPBUY1x2_W, WHIMSYSHOPBUY1x2_H)

WHIMSYSHOPBUY1x3_X = X * 0.72
WHIMSYSHOPBUY1x3_Y = Y * 0.2
WHIMSYSHOPBUY1x3_W = X * 0.2
WHIMSYSHOPBUY1x3_H = Y * 0.3
WHIMSYSHOPBUY1x3_REGION = Region(WHIMSYSHOPBUY1x3_X, WHIMSYSHOPBUY1x3_Y, WHIMSYSHOPBUY1x3_W, WHIMSYSHOPBUY1x3_H)

BUYSHARD_X = X * 0.6
BUYSHARD_Y = Y * 0.85
BUYSHARD_REGION = Region(BUYSHARD_X, BUYSHARD_Y, CLICK_BLOCK_W, CLICK_BLOCK_H)

SHARDBOUGHT_X = X * 0.27
SHARDBOUGHT_Y = Y * 0.18
SHARDBOUGHT_W = X * 0.05
SHARDBOUGHT_H = Y * 0.1
SHARDBOUGHT_REGION = Region(SHARDBOUGHT_X, SHARDBOUGHT_Y, SHARDBOUGHT_W, SHARDBOUGHT_H)

SHARDBOUGHTOK_X = X * 0.5
SHARDBOUGHTOK_Y = Y * 0.7
SHARDBOUGHTOK_REGION = Region(SHARDBOUGHTOK_X, SHARDBOUGHTOK_Y, CLICK_BLOCK_W, CLICK_BLOCK_H)

INFEVERPAGE_X = X * 0.59
INFEVERPAGE_Y = Y * 0.07
INFEVERPAGE_W = X * 0.025
INFEVERPAGE_H = Y * 0.05
INFEVERPAGE_REGION = Region(INFEVERPAGE_X, INFEVERPAGE_Y, INFEVERPAGE_W, INFEVERPAGE_H)

GOFEVERLATER_X = X * 0.38
GOFEVERLATER_Y = Y * 0.92
GOFEVERLATER_REGION = Region(GOFEVERLATER_X, GOFEVERLATER_Y, CLICK_BLOCK_W, CLICK_BLOCK_H)

NRGNOTENOUGH_X = X * 0.27
NRGNOTENOUGH_Y = Y * 0.18
NRGNOTENOUGH_W = X * 0.05
NRGNOTENOUGH_H = Y * 0.1
NRGNOTENOUGH_REGION = Region(NRGNOTENOUGH_X, NRGNOTENOUGH_Y, NRGNOTENOUGH_W, NRGNOTENOUGH_H)

NRGRESTOREYES_X = X * 0.6
NRGRESTOREYES_Y = Y * 0.72
NRGRESTOREYES_REGION = Region(NRGRESTOREYES_X, NRGRESTOREYES_Y, CLICK_BLOCK_W, CLICK_BLOCK_H)

NRGRESTORENO_X = X * 0.4
NRGRESTORENO_Y = Y * 0.72
NRGRESTORENO_REGION = Region(NRGRESTORENO_X, NRGRESTORENO_Y, CLICK_BLOCK_W, CLICK_BLOCK_H)

NRGRESTOREPAGE_X = X * 0.18
NRGRESTOREPAGE_Y = Y * 0.08
NRGRESTOREPAGE_W = X * 0.05
NRGRESTOREPAGE_H = Y * 0.1
NRGRESTOREPAGE_REGION = Region(NRGRESTOREPAGE_X, NRGRESTOREPAGE_Y, NRGRESTOREPAGE_W, NRGRESTOREPAGE_H)

USEVISIORE_X = X * 0.33
USEVISIORE_Y = Y * 0.69
USEVISIORE_W = X * 0.05
USEVISIORE_H = Y * 0.05
USEVISIORE_REGION = Region(USEVISIORE_X, USEVISIORE_Y, USEVISIORE_W, USEVISIORE_H)

USEITEM_X = X * 0.5
USEITEM_Y = Y * 0.55
USEITEM_REGION = Region(USEITEM_X, USEITEM_Y, CLICK_BLOCK_W, CLICK_BLOCK_H)

USEITEMBIGDRAGDROPFROM_X = X * 0.5
USEITEMBIGDRAGDROPFROM_Y = Y * 0.7
USEITEMBIGDRAGDROPFROM_REGION = Region(USEITEMBIGDRAGDROPFROM_X, USEITEMBIGDRAGDROPFROM_Y, X * 0.1, Y * 0.1)
USEITEMBIGDRAGDROPTO_X = X * 0.5
USEITEMBIGDRAGDROPTO_Y = Y * 0.35
USEITEMBIGDRAGDROPTO_REGION = Region(USEITEMBIGDRAGDROPTO_X, USEITEMBIGDRAGDROPTO_Y, X * 0.1, Y * 0.1)

USEITEMROW1_X = X * 0.23
USEITEMROW1_Y = Y * 0.42
USEITEMROW1_W = X * 0.1
USEITEMROW1_H = Y * 0.1
USEITEMROW1_REGION = Region(USEITEMROW1_X, USEITEMROW1_Y, USEITEMROW1_W, USEITEMROW1_H)

USEITEMROW2_X = X * 0.23
USEITEMROW2_Y = Y * 0.68
USEITEMROW2_W = X * 0.1
USEITEMROW2_H = Y * 0.1
USEITEMROW2_REGION = Region(USEITEMROW2_X, USEITEMROW2_Y, USEITEMROW2_W, USEITEMROW2_H)

USEITEMADDROW1_X = X * 0.68
USEITEMADDROW1_Y = Y * 0.38
USEITEMADDROW1_W = X * 0.08
USEITEMADDROW1_H = Y * 0.15
USEITEMADDROW1_REGION = Region(USEITEMADDROW1_X, USEITEMADDROW1_Y, USEITEMADDROW1_W, USEITEMADDROW1_H)

USEITEMADDROW2_X = X * 0.68
USEITEMADDROW2_Y = Y * 0.66
USEITEMADDROW2_W = X * 0.08
USEITEMADDROW2_H = Y * 0.15
USEITEMADDROW2_REGION = Region(USEITEMADDROW2_X, USEITEMADDROW2_Y, USEITEMADDROW2_W, USEITEMADDROW2_H)

RESTORENRG_X = X * 0.67
RESTORENRG_Y = Y * 0.92
RESTORENRG_REGION = Region(RESTORENRG_X, RESTORENRG_Y, CLICK_BLOCK_W, CLICK_BLOCK_H)

NRGRESTORED_REGION = Region(NRGNOTENOUGH_X, NRGNOTENOUGH_Y, NRGNOTENOUGH_W, NRGNOTENOUGH_H)

NRGRESTOREDOK_X = X * 0.5
NRGRESTOREDOK_Y = Y * 0.7
NRGRESTOREDOK_REGION = Region(NRGRESTOREDOK_X, NRGRESTOREDOK_Y, CLICK_BLOCK_W, CLICK_BLOCK_H)

INMULTIEMBARKPAGE_X = X * 0.08
INMULTIEMBARKPAGE_Y = Y * 0.15
INMULTIEMBARKPAGE_W = X * 0.08
INMULTIEMBARKPAGE_H = Y * 0.1
INMULTIEMBARKPAGE_REGION = Region(INMULTIEMBARKPAGE_X, INMULTIEMBARKPAGE_Y, INMULTIEMBARKPAGE_W, INMULTIEMBARKPAGE_H)

CONFIRMEMBARK_REGION = Region(NRGNOTENOUGH_X, NRGNOTENOUGH_Y, NRGNOTENOUGH_W, NRGNOTENOUGH_H)

--CONFIRMEMBARKOK_X = X * 0.5
--CONFIRMEMBARKOK_Y = Y * 0.7
CONFIRMEMBARKOK_X = X * 0.6
CONFIRMEMBARKOK_Y = Y * 0.72
CONFIRMEMBARKOK_REGION = Region(CONFIRMEMBARKOK_X, CONFIRMEMBARKOK_Y, CLICK_BLOCK_W, CLICK_BLOCK_H)

FRIENDREQUESTS_X = X * 0.22
FRIENDREQUESTS_Y = Y * 0.02
FRIENDREQUESTS_W = X * 0.05
FRIENDREQUESTS_H = Y * 0.1
FRIENDREQUESTS_REGION = Region(FRIENDREQUESTS_X, FRIENDREQUESTS_Y, FRIENDREQUESTS_W, FRIENDREQUESTS_H)

REQUESTCANCEL_X = X * 0.35
REQUESTCANCEL_Y = Y * 0.9
REQUESTCANCEL_REGION = Region(REQUESTCANCEL_X, REQUESTCANCEL_Y, CLICK_BLOCK_W, CLICK_BLOCK_H)